name: Build and publish to DockerHub

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish "ingress-default-backend" to DockerHub (latest)
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.2
      with:
        name: progamesigner/ingress-default-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: "!contains(github.ref, 'refs/tags/v')"
    - name: Publish "ingress-default-backend" to DockerHub
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.2
      with:
        name: progamesigner/ingress-default-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
      if: "contains(github.ref, 'refs/tags/v')"
