name: Build and publish to DockerHub

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish "ingress-default-backend" to DockerHub (latest)
      uses: docker/build-push-action@v1
      with:
        add_git_labels: true
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: progamesigner/ingress-default-backend
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
      if: "!contains(github.ref, 'refs/tags/v')"
    - name: Publish "ingress-default-backend" to DockerHub
      uses: docker/build-push-action@v1
      with:
        add_git_labels: true
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: progamesigner/ingress-default-backend
        tag_with_ref: latest
        username: ${{ secrets.DOCKER_USERNAME }}
      if: "contains(github.ref, 'refs/tags/v')"
