name: Build and publish to DockerHub

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish "ingress-default-backend" to DockerHub (latest)
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: ${{ github.repository }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
      if: "!contains(github.ref, 'refs/tags/v')"
    - name: Publish "ingress-default-backend" to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: ${{ github.repository }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
      if: "contains(github.ref, 'refs/tags/v')"
